### ISSUE TITLE
[feat] Move from MVC Architecture to Domain-Driven Design (DDD)

### ISSUE THREAD

**Issue by zhravan** [shravan20/neonode-oss-quick-starter#23]
### Description

The current architecture of Neonode is based on the Model-View-Controller (MVC) pattern. While MVC has been effective in structuring the application, the increasing complexity of the business logic and domain models suggests that a shift to Domain-Driven Design (DDD) could provide a more scalable, maintainable, and domain-focused architecture.

### Feature Request:

**Purpose**:  Refactor the Neonode architecture to adopt Domain-Driven Design (DDD) principles, aiming for better separation of concerns, encapsulation of business logic, and alignment with complex domain requirements.

**Key Changes**:

- Introduce Domain Layer for encapsulating core business logic and domain models.
- Separate Application Layer for handling application-specific logic, use cases, and orchestration.
- Infrastructure Layer to deal with external systems (e.g., databases, APIs).
- Repository Pattern to abstract data access logic, separating it from domain logic.
- Implement Aggregates and Entities for encapsulating complex domain rules.
- Refactor existing controllers, services, and models to align with DDD principles.

Discussion Points:

- **Migration Strategy**: How do we transition from MVC to DDD without disrupting current functionality?
- Gradual refactoring vs. complete overhaul.
- Testing strategies during the migration.
- Compatibility with existing modules.
- Potential codebase restructuring.
- Documentation and guidelines for contributing with DDD.
- Tooling and Libraries: Do we need new libraries or tools to support DDD?

Would love to discuss and hear input from the community to assess the overall sentiment and gather ideas.

**Comment by zawa999** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer
